version: "3"  

services:
  app1:
    build: ./app1
    ports:
      - "5001:5000"

  nginx:
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/server.crt:/etc/nginx/server.crt
      - ./nginx/server.key:/etc/nginx/server.key
    depends_on:
      - app1
